import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#E7EEFA",
  },
  header: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingHorizontal: 20,
    paddingVertical: 15,
    backgroundColor: "#E7EEFA",
    borderBottomWidth: 1,
    borderBottomColor: "#E0E0E0",
    paddingTop: 30,
  },
  backButton: {
    padding: 8,
  },
  headerTitle: {
    fontSize: 20,
    fontFamily: "DMSans_700Bold",
    color: "#000",
  },
  headerSpacer: {
    width: 40,
  },
  deleteHeaderButton: {
    padding: 8,
  },
  loadingContainer: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
  },
  loadingText: {
    marginTop: 10,
    fontSize: 16,
    color: "#666",
    fontFamily: "DMSans_400Regular",
  },
  errorContainer: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
  },
  errorText: {
    fontSize: 18,
    color: "#666",
    fontFamily: "DMSans_400Regular",
  },
  content: {
    flex: 1,
  },
  productImageSection: {
    backgroundColor: "#FFF",
    padding: 20,
    marginBottom: 12,
  },
  imageContainer: {
    alignItems: "center",
    marginBottom: 20,
    position: "relative",
  },
  productImage: {
    width: 200,
    height: 200,
    borderRadius: 12,
    backgroundColor: "#F0F0F0",
  },
  expiringBadge: {
    position: "absolute",
    top: -8,
    right: 60,
    backgroundColor: "#FFF2E5",
    borderRadius: 16,
    paddingHorizontal: 10,
    paddingVertical: 6,
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
    borderWidth: 1,
    borderColor: "#FF8C42",
  },
  expiringText: {
    fontSize: 12,
    fontFamily: "DMSans_400Regular",
    color: "#FF8C42",
  },
  basicInfo: {
    alignItems: "center",
  },
  productName: {
    fontSize: 24,
    fontFamily: "DMSans_700Bold",
    color: "#000",
    textAlign: "center",
    marginBottom: 4,
  },
  productCategory: {
    fontSize: 16,
    fontFamily: "DMSans_400Regular",
    color: "#666",
    marginBottom: 16,
  },
  stockStatusContainer: {
    alignItems: "center",
  },
  stockBadge: {
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 16,
    marginBottom: 8,
  },
  stockBadgeText: {
    fontSize: 14,
    fontFamily: "DMSans_400Regular",
  },
  stockCount: {
    fontSize: 20,
    fontFamily: "DMSans_700Bold",
    color: "#000",
  },
  section: {
    backgroundColor: "#FFF",
    padding: 20,
    marginBottom: 12,
  },
  sectionTitle: {
    fontSize: 18,
    fontFamily: "DMSans_700Bold",
    color: "#000",
    marginBottom: 16,
  },
  pricingGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    justifyContent: "space-between",
  },
  priceItem: {
    width: "48%",
    marginBottom: 16,
  },
  priceLabel: {
    fontSize: 14,
    fontFamily: "DMSans_400Regular",
    color: "#666",
    marginBottom: 4,
  },
  priceValue: {
    fontSize: 18,
    fontFamily: "DMSans_700Bold",
    color: "#000",
  },
  profitValue: {
    color: "#4CAF50",
  },
  stockGrid: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginBottom: 16,
  },
  stockItem: {
    flex: 1,
    marginRight: 10,
  },
  stockLabel: {
    fontSize: 14,
    fontFamily: "DMSans_400Regular",
    color: "#666",
    marginBottom: 4,
  },
  stockValue: {
    fontSize: 16,
    fontFamily: "DMSans_700Bold",
    color: "#000",
  },
  lowStockAlert: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#FFF2E5",
    padding: 12,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: "#FF8C42",
  },
  lowStockText: {
    fontSize: 14,
    fontFamily: "DMSans_400Regular",
    color: "#FF8C42",
    marginLeft: 8,
    flex: 1,
  },
  detailsGrid: {
    gap: 16,
  },
  detailItem: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  detailLabel: {
    fontSize: 16,
    fontFamily: "DMSans_400Regular",
    color: "#666",
    flex: 1,
  },
  detailValue: {
    fontSize: 16,
    fontFamily: "DMSans_400Regular",
    color: "#000",
    flex: 2,
    textAlign: "right",
  },
  expiringDate: {
    color: "#FF8C42",
  },
  supplierInfo: {
    gap: 16,
  },
  supplierItem: {
    flexDirection: "row",
    alignItems: "center",
  },
  supplierTextContainer: {
    marginLeft: 12,
    flex: 1,
  },
  supplierLabel: {
    fontSize: 14,
    fontFamily: "DMSans_400Regular",
    color: "#666",
    marginBottom: 2,
  },
  supplierValue: {
    fontSize: 16,
    fontFamily: "DMSans_400Regular",
    color: "#000",
  },
  actionSection: {
    backgroundColor: "#FFF",
    padding: 20,
    marginBottom: 12,
    gap: 12,
  },
  editButton: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#F0F7FF",
    borderRadius: 12,
    paddingVertical: 14,
    borderWidth: 1,
    borderColor: "#007AFF",
    gap: 8,
  },
  editButtonText: {
    fontSize: 16,
    fontFamily: "DMSans_400Regular",
    color: "#1155CC",
  },
  deleteActionButton: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#FFE5E5",
    borderRadius: 12,
    paddingVertical: 14,
    borderWidth: 1,
    borderColor: "#FF6B6B",
    gap: 8,
  },
  deleteActionButtonText: {
    fontSize: 16,
    fontFamily: "DMSans_400Regular",
    color: "#FF6B6B",
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: "rgba(0, 0, 0, 0.5)",
    justifyContent: "center",
    alignItems: "center",
    paddingHorizontal: 20,
  },
  deleteModal: {
    backgroundColor: "#FFF",
    borderRadius: 16,
    padding: 24,
    width: "100%",
    maxWidth: 400,
  },
  deleteModalHeader: {
    alignItems: "center",
    marginBottom: 16,
  },
  deleteModalTitle: {
    fontSize: 20,
    fontFamily: "DMSans_700Bold",
    color: "#000",
    marginTop: 8,
  },
  deleteModalMessage: {
    fontSize: 16,
    fontFamily: "DMSans_400Regular",
    color: "#666",
    textAlign: "center",
    lineHeight: 24,
    marginBottom: 24,
  },
  deleteModalButtons: {
    flexDirection: "row",
    gap: 12,
  },
  cancelButton: {
    flex: 1,
    backgroundColor: "#F8F9FA",
    borderRadius: 12,
    paddingVertical: 14,
    alignItems: "center",
    borderWidth: 1,
    borderColor: "#E0E0E0",
  },
  cancelButtonText: {
    fontSize: 16,
    fontFamily: "DMSans_400Regular",
    color: "#666",
  },
  deleteButton: {
    flex: 1,
    backgroundColor: "#FF6B6B",
    borderRadius: 12,
    paddingVertical: 14,
    alignItems: "center",
    flexDirection: "row",
    justifyContent: "center",
    gap: 6,
  },
  deleteButtonText: {
    fontSize: 16,
    fontFamily: "DMSans_400Regular",
    color: "#FFF",
  },
  disabledButton: {
    opacity: 0.7,
  },
  bottomPadding: {
    height: 20,
  },
});
