import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#FFF",
  },
  header: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingHorizontal: 20,
    paddingVertical: 16,
    backgroundColor: "#FFF",
  },
  headerTitle: {
    fontSize: 24,
    fontFamily: "DMSans_700Bold",
    color: "#1C1C1C",
  },
  closeButton: {
    padding: 4,
  },
  loadingContainer: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
  },
  loadingText: {
    marginTop: 10,
    fontSize: 16,
    color: "#666",
    fontFamily: "DMSans_400Regular",
  },
  errorContainer: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
  },
  errorText: {
    fontSize: 18,
    color: "#666",
    fontFamily: "DMSans_400Regular",
  },
  content: {
    flex: 1,
  },
  imageContainer: {
    alignItems: "center",
    paddingVertical: 20,
    backgroundColor: "#FFF",
  },
  productImage: {
    width: 180,
    height: 150,
    resizeMode: "contain",
    backgroundColor: "#FFF",
  },
  section: {
    paddingHorizontal: 20,
    paddingTop: 20,
    paddingBottom: 4,
    backgroundColor: "#FFF",
  },
  sectionTitle: {
    fontSize: 14,
    fontFamily: "DMSans_400Regular",
    color: "#000000",
    letterSpacing: 1,
    textTransform: "uppercase",
    marginBottom: 8,
  },
  row: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingVertical: 14,
    borderBottomWidth: 1,
    borderBottomColor: "#F0F0F0",
  },
  rowLabel: {
    fontSize: 14,
    fontFamily: "DMSans_400Regular",
    color: "#6E6E6E",
  },
  rowValue: {
    fontSize: 14,
    fontFamily: "DMSans_400Regular",
    color: "#1C1C1C",
    textAlign: "right",
    flex: 1,
    marginLeft: 16,
  },
  bottomContainer: {
    padding: 20,
    paddingBottom: 32,
    backgroundColor: "#FFF",
  },
  editButton: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#1155CC",
    borderRadius: 14,
    paddingVertical: 16,
    gap: 10,
  },
  editButtonText: {
    fontSize: 16,
    fontFamily: "DMSans_400Regular",
    color: "#F2F2F2",
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: "rgba(0, 0, 0, 0.5)",
    justifyContent: "center",
    alignItems: "center",
    paddingHorizontal: 20,
  },
  deleteModal: {
    backgroundColor: "#FFF",
    borderRadius: 16,
    padding: 24,
    width: "100%",
    maxWidth: 400,
  },
  deleteModalHeader: {
    alignItems: "center",
    marginBottom: 16,
  },
  deleteModalTitle: {
    fontSize: 20,
    fontFamily: "DMSans_700Bold",
    color: "#000",
    marginTop: 8,
  },
  deleteModalMessage: {
    fontSize: 16,
    fontFamily: "DMSans_400Regular",
    color: "#666",
    textAlign: "center",
    lineHeight: 24,
    marginBottom: 24,
  },
  deleteModalButtons: {
    flexDirection: "row",
    gap: 12,
  },
  cancelButton: {
    flex: 1,
    backgroundColor: "#F8F9FA",
    borderRadius: 12,
    paddingVertical: 14,
    alignItems: "center",
    borderWidth: 1,
    borderColor: "#E0E0E0",
  },
  cancelButtonText: {
    fontSize: 16,
    fontFamily: "DMSans_400Regular",
    color: "#666",
  },
  deleteButton: {
    flex: 1,
    backgroundColor: "#FF6B6B",
    borderRadius: 12,
    paddingVertical: 14,
    alignItems: "center",
    flexDirection: "row",
    justifyContent: "center",
    gap: 6,
  },
  deleteButtonText: {
    fontSize: 16,
    fontFamily: "DMSans_400Regular",
    color: "#FFF",
  },
  disabledButton: {
    opacity: 0.7,
  },
});
